server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

  liquibase:
    enabled: false
    change-log: file:migrations/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY:} # Use env variable. DO NOT KEEP TOKEN HERE
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
  bot:
    url: http://localhost:8080
  scheduler:
    interval: 20s
    linkcheckinterval: 2m
  access-type: jdbc
