server:
  port: 8080

spring:
  application:
    name: bot
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "bot-group"
      auto-offset-reset: earliest

app:
  internal-token: ${INTERNAL_API_TOKEN:dev-internal-token}
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN:}
    update-listener-sleep: 1s
    debug: false
  scrapper:
    url: http://localhost:8081
  access-type: redis
  kafka:
    topic-name: "link.processed-updates"
    schema-registry-url: "http://localhost:8083"
    retry-attempts: 3
  cache:
    list-links-ttl: 10m
    context-ttl: 30m
  rate-limit:
    capacity: 10
    refresh-period: 1m

resilience4j:
  ratelimiter:
    instances:
      botApiLimit:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0

management:
  server:
    port: 8011
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        command_duration_ms_total: true
