server:
  port: 8080

spring:
  application:
    name: bot
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "bot-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "backend.academy.linktracker.bot.infrastructure.api.dtos.LinkUpdate"

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    url: http://localhost:8081
  access-type: redis
  kafka:
    topic-name: "link_updates"
    retry-attempts: 3
  cache:
    list-links-ttl: 10m
    context-ttl: 30m
