server:
  port: 8080

spring:
  application:
    name: bot
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  data:
    redis:
      host: localhost
      port: 6379

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    url: http://localhost:8081
  access-type: redis
